import { colorThemes, designTokens, type ColorTheme } from "./tokens";

type TokenTree = {
  readonly [key: string]: string | number | TokenTree;
};

function kebabCase(value: string) {
  return value.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

function flattenTokens(
  tree: TokenTree,
  path: string[] = []
): Array<readonly [string, string | number]> {
  return Object.entries(tree).flatMap(([key, value]) => {
    const nextPath = [...path, kebabCase(key)];

    if (typeof value === "object") {
      return flattenTokens(value, nextPath);
    }

    return [[`--mt-${nextPath.join("-")}`, value] as const];
  });
}

function cssValue(name: string, value: string | number) {
  if (typeof value === "number") {
    if (name.includes("-weight-")) {
      return String(value);
    }

    return `${value}px`;
  }

  return value;
}

export function renderDesignTokenCss() {
  const declarations = flattenTokens(designTokens as TokenTree)
    .map(([name, value]) => `  ${name}: ${cssValue(name, value)};`)
    .join("\n");
  const semanticColorNames = Object.keys(
    colorThemes.light
  ) as Array<keyof typeof colorThemes.light>;
  const renderThemeAliases = (theme: ColorTheme) =>
    semanticColorNames
      .map((name) => {
        const cssName = kebabCase(name);
        return `  --mt-color-${cssName}: var(--mt-color-theme-${theme}-${cssName});`;
      })
      .join("\n");

  return `/* Generated by @meadtools/design-tokens. Do not edit directly. */\n:root {\n${declarations}\n${renderThemeAliases("light")}\n}\n\n.dark {\n${renderThemeAliases("dark")}\n}\n`;
}
