import {
  designTokens,
  webColorChannels,
  type ColorTheme
} from "./tokens";

type TokenTree = {
  readonly [key: string]: string | number | TokenTree;
};

export function kebabCase(value: string) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([a-zA-Z])([0-9])/g, "$1-$2")
    .toLowerCase();
}

function flattenTokens(
  tree: TokenTree,
  path: string[] = []
): Array<readonly [string, string | number]> {
  return Object.entries(tree).flatMap(([key, value]) => {
    const nextPath = [...path, kebabCase(key)];

    if (typeof value === "object") {
      return flattenTokens(value, nextPath);
    }

    return [[`--mt-${nextPath.join("-")}`, value] as const];
  });
}

function cssValue(value: string | number) {
  if (typeof value === "number") {
    return `${value}px`;
  }

  return value;
}

function renderWebChannels(theme: ColorTheme) {
  return Object.entries(webColorChannels[theme])
    .map(
      ([name, value]) =>
        `  --mt-web-${theme}-${kebabCase(name)}: ${value};`
    )
    .join("\n");
}

export function renderDesignTokenCss() {
  const declarations = flattenTokens({
    color: {
      brand: designTokens.color.brand
    },
    web: designTokens.web,
    spacing: designTokens.spacing,
    radius: designTokens.radius,
    typography: designTokens.typography
  } as TokenTree)
    .map(([name, value]) => `  ${name}: ${cssValue(value)};`)
    .join("\n");

  return `/* Generated by @meadtools/design-tokens. Do not edit directly. */\n:root {\n${declarations}\n${renderWebChannels("light")}\n${renderWebChannels("dark")}\n}\n`;
}
